### ISSUE TITLE
 Call to undefined function Copyleaks\isJson()

### ISSUE THREAD

**Issue by angelxmoreno** [Copyleaks/PHP-Plagiarism-Checker#1]
It seems like the code relies on the inclusion of the custom autoload file and not the composer autoloader.

**Comment by eladbitton** [comment]
I am checking this out. What version of php do you use?

**Comment by angelxmoreno** [comment]
PHP 5.6.31

**Comment by eladbitton** [comment]
We currently support PHP 7.0 and up.
I suggest you to clone the repo and fix this few minor bugs and it should work for you as well.

**Comment by angelxmoreno** [comment]
Using PHP 7.2.3 I am still getting the same errors. The issue is composer related, not PHP related. Even the example files throw the same errors unless the package autoload.php is included. Using composer, including the composer level autoload.php should be sufficient under normal circumstances.

**Comment by elir-copyleaks** [comment]
Hi Angel,

A new version ( 1.3 ) that moves the function isJson out of autoload.php is now available.
Please let us know if this works for you.

Thanks, the Copyleaks team
