### ISSUE TITLE
Case sensitive error

### ISSUE THREAD

**Issue by agmaxwellh** [Copyleaks/PHP-Plagiarism-Checker#10]
https://github.com/Copyleaks/PHP-Plagiarism-Checker/blob/cad9a2565dd3184817f0f4db91fd03524428e51e/src/Models/Index.php#L37

In "\src\Models\Index.php" at line 37 there is: include_once('exceptions/index.php');.
Note that the correct path should be 'exceptions/Index.php'.

The path 'exceptions/index.php' without capital letter ( i )causes problem in case sensitive systems.

I encounter "ErrorException include_once(exceptions/index.php): failed to open stream: No such file or directory" trying to deploying to a linux server. (Ubuntu 20.04 - Composer 2.1 - PHP 7.4 - Laravel 8.40)

Please, fix include_once("exceptions/index.php"); with include_once("exceptions/Index.php");

**Comment by CL-BayanAbuawad** [comment]
@agmaxwellh thank you for your report, the bug was fixed and released (release 3.0.2).
