### ISSUE TITLE
Error : Syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by demootesting** [Copyleaks/PHP-Plagiarism-Checker#11]
Syntax Error - Unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST). Error is during PHP Integration.

**Comment by vidhyabala** [comment]
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in vendor\copyleaks\php-plagiarism-checker\src\Models\CopyleaksAuthToken.php on line 30

Am also getting the same issue. Can anyone help me out in this?

**Comment by vidhyabala** [comment]
The above issue is solved by using the higher version of PHP i.e above PHP 7.3. 

But now am getting the security error as **result:
"Sensitive Data Protection is not enabled to your account."**

**Comment by CL-BayanAbuawad** [comment]
@demootesting update to PHP 7.3 or above should solve the problem for you as @vidhyabala suggested.

@vidhyabala removing the SubmissionSensitiveData object (optional param) from the SubmissionProperties object should solve the problem for you, I updated the demo to not include that anymore.
![image](https://user-images.githubusercontent.com/58811253/128130251-efd78c7a-b91a-4a57-b764-3c2cc108f09b.png)
