### ISSUE TITLE
Error: Copyleaks SDK Error

### ISSUE THREAD

**Issue by demootesting** [Copyleaks/PHP-Plagiarism-Checker#12]
Copyleaks SDK Error is displaying while executing "TEST_submitUrl", "TEST_submitFile" & "TEST_submitOcrFile" functions (simultaneously Or One by One), because of this error "TEST_export" function is unable to deliver the result.

**Comment by vidhyabala** [comment]
Please share if there is any working example to send a url to scan in php. That will be very helpful. Am not sure where to send the URL to scan and how to use webooks.

**Comment by CL-BayanAbuawad** [comment]
@demootesting @vidhyabala can you please check my replay [here](https://github.com/Copyleaks/PHP-Plagiarism-Checker/issues/11#issuecomment-892389807) and let me know if this solve the problem for you
