### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by angelxmoreno** [Copyleaks/PHP-Plagiarism-Checker#2]
Any ideas when a stable release tag will be published? Our minimum-stability setting on composer forbids non-stable tags

**Comment by elir-copyleaks** [comment]
Hi Angel,

We've published a v1.1 stable tag. Could you please check if composer allows it now?

Thanks, The Copyleaks team.

**Comment by angelxmoreno** [comment]
All is well now! TYVM!
