### ISSUE TITLE
Incorrect api endpoint for checking credits balance

### ISSUE THREAD

**Issue by NickLorimer** [Copyleaks/PHP-Plagiarism-Checker#5]
When checking credit balance, the api endpoint used is: 'https://api.copyleaks.com/v1/account/count-credits' where is should be: 'https://api.copyleaks.com/v1/(education, business, etc)/count-credits.

**Comment by elir-copyleaks** [comment]
Hi @NickLorimer,

Commit 56e6bf97b220e4fff5f57045e7e90d890f100996 should fix this issue. Please take the latest version.
Thanks for finding this issue.

**Comment by NickLorimer** [comment]
@elir-copyleaks Just though that I'd point out that the latest release (1.3) is a few commits behind the latest version, so when using composer to install the SDK I'm unable to use the most recent version.

**Comment by elir-copyleaks** [comment]
@NickLorimer. Thanks. New release available 1.4. Hope this works for you.
