### ISSUE TITLE
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in D:\laravel\as\vendor\copyleaks\php-plagiarism-checker\src\Models\CopyleaksAuthToken.php on line 31

### ISSUE THREAD

**Issue by anujsulakhiya** [Copyleaks/PHP-Plagiarism-Checker#9]
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in D:\laravel\as\vendor\copyleaks\php-plagiarism-checker\src\Models\CopyleaksAuthToken.php on line 31

**Comment by CL-BayanAbuawad** [comment]
@anujsulakhiya  I can't recreate the issue on my side, can you share your usage code with me?

**Comment by CL-BayanAbuawad** [comment]
@anujsulakhiya upgrade to PHP 7.3 or higher should solve the problem for you
